[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.28"
include_dir = "0.7.3"
rapid_web = { version = "0.4.0", path = "../rapid/crates/rapid-web" }
# Rapid binary
[[bin]]
name = "api"
path = "app/api/root.rs"
